[project]
name = ""
version = "0.0.1"
dependencies = [
  "magic-wormhole  ==  0.20.0",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
